#!/usr/bin/env python
from setuptools import find_namespace_packages, setup

setup(
    name="maua",
    version="0.5",
    description="Deep learning toolkit for image, video, and audio synthesis",
    author="Hans Brouwer",
    author_email="hans@wavefunk.xyz",
    url="https://github.com/maua-maua-maua/maua",
    packages=find_namespace_packages(
        include=["maua*"],
        exclude=[
            "maua.submodules.mmflow.tests*",
            "maua.submodules.mmflow.docs*",
            "maua.submodules.SwinIR.testsets*",
            "maua.submodules.VQGAN.data*",
            "maua.submodules.pycuda.bpl-subset*",
        ],
    ),
    package_data={
        "": ["*.yml", "*.yaml"],
        "maua.submodules.waifu2x*": ["*.zip", "*.7z"],
        "maua.submodules.stable_diffusion*": ["configs/*"],
    },
    include_package_data=True,
    python_requires=">=3.12",
    install_requires=[
        "accelerate",
        "auraloss",
        "av",
        "basicsr",
        "bitsandbytes",
        "cached-conv",  # audio/rave
        "clean-fid",
        "click",
        "cython",
        "CLIP @ git+https://github.com/StarTwi/CLIP.git@bb9d976819f587c37bd31b8fafe13358fcf8fdd7",
        "decord",
        "deep_translator",
        "diffusers",
        "dill",
        "easydict",
        "effortless_config",
        "einops",
        "ffmpeg_python",
        "filetype",
        "fire",  # audio/jukebox CLIs
        "ftfy",
        "gdown",
        "gfpgan",
        "gin-config",  # audio/waveshaping
        "glide_text2im @ git+https://github.com/openai/glide-text2im",
        "glumpy",
        "gputil",
        "h5py",
        "huggingface_hub",
        "icetk",
        "imageio_ffmpeg",
        "joblib",
        "jsonmerge",
        "kornia",
        "librosa",
        "lpips",
        "madmom @ git+https://github.com/CPJKU/madmom.git",
        "matplotlib",
        "medpy",
        "mmcv-full",
        "mmflow",
        "more_itertools",
        "mpi4py",  # audio/jukebox distributed setup
        "ninja",
        "npy_append_array",
        "numba",
        "numpy",
        "omegaconf",
        "opencv-python",
        "openunmix",
        "pandas",
        "pillow",
        "prdc",
        "py7zr",
        "pycuda",
        "pyglet",
        "pyopengl",
        "pyspng",
        "pytorch-lightning<2",  # latent-diffusion / taming submodules use PL 1.x APIs (utilities.distributed)
        "pytorch-msssim",
        "pytorch_optimizer",
        "PyYaml",
        "realesrgan",
        "requests",
        "resampy",
        "resize_right",
        "scikit-learn",
        "scipy",
        "seaborn",
        "sentencepiece",
        "setuptools<81",  # StyleGAN custom ops (GAN/nv) and mmcv import pkg_resources (removed in 81+)
        "soundfile",
        "SwissArmyTransformer",
        "tensorboard",
        "tensorboardX",
        "termcolor",
        "timm",
        "torch",
        "torchaudio",
        "torchcrepe",
        "torchcubicspline @ git+https://github.com/patrick-kidger/torchcubicspline.git",
        "torchdiffeq",
        "torchmetrics",
        "torch_optimizer",
        "torchtext",
        "torchtyping",
        "torchvision",
        "tqdm",
        "transformers",
        "udls",  # audio/rave dataset tooling
        "unidecode",
        "wandb>=0.16.0",  # older wandb pulls pathtools, whose setup uses stdlib imp (removed in 3.12)
        "youtokentome",
    ],
)
